@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"
String imageTag = 'v' + version

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/csiaddons-k8s-sidecar:' + imageTag ): 'olcne/csiaddons-k8s-sidecar:' + imageTag],
        platforms: [ 'ol9'],
	PLATFORM_FILTER: 'ol9',
        architectures: ['x86_64', 'aarch64'],
        buildScript: "sh olm/build-image.sh",
)
